### ISSUE TITLE
com.github.javaparser.ast.expr.FieldAccessExpr cannot be cast to com.github.javaparser.ast.expr.NameExpr

### ISSUE THREAD

**Issue by teknogeek** [helios-decompiler/Helios#27]
```
Scope is class com.github.javaparser.ast.expr.ArrayAccessExpr lS.h[n3]
java.lang.ClassCastException: com.github.javaparser.ast.expr.FieldAccessExpr cannot be cast to com.github.javaparser.ast.expr.NameExpr
	at com.heliosdecompiler.helios.tasks.DecompileTask.recursivelyHandleNameExpr(DecompileTask.java:728)
	at com.heliosdecompiler.helios.tasks.DecompileTask.access$000(DecompileTask.java:57)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:444)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:73)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:796)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:274)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:69)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:788)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:487)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:407)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:542)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:53)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:169)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:527)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:459)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:567)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.stmt.IfStmt.accept(IfStmt.java:61)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:169)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:527)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:567)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:289)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:111)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:231)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:239)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:85)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:260)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:209)
	at com.heliosdecompiler.helios.tasks.DecompileTask$1.visit(DecompileTask.java:206)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:84)
	at com.heliosdecompiler.helios.tasks.DecompileTask.handle(DecompileTask.java:205)
	at com.heliosdecompiler.helios.tasks.DecompileTask.run(DecompileTask.java:138)
	at java.lang.Thread.run(Thread.java:745)
```

when decompiling with Procyon this seems to cause the window to be blank where there should be code

**Comment by teknogeek** [comment]
Additionally, it seems that decompiling a different file with the same decompiler and then decompiling the first file again causes it to succeed. This is the same for any other decompiler that ends up experiencing the same issue
